import type {
  Applicant,
  Booking,
  ChatMessage,
  Client,
  Room,
  Specialist,
  Thread,
} from "./types";

/**
 * Front-end data layer.
 *
 * Everything the UI reads goes through the selectors at the bottom of this
 * file, so swapping these arrays for real queries later is a one-file change.
 */

export const CURRENT_CLIENT_ID = "cl-01";

export const rooms: Room[] = [
  {
    id: "basic",
    name: "Basic Room",
    tagline: "Everyday upkeep, vetted and reliable.",
    priceMonthly: 29,
    perks: [
      "Access to vetted Basic-room specialists",
      "Up to 2 bookings per month",
      "In-app chat with photo sharing",
      "Standard scheduling (48h ahead)",
      "Secure in-chat payments",
    ],
    visitFeeRange: [35, 55],
    specialistCount: 84,
    seatsLeft: 120,
  },
  {
    id: "premium",
    name: "Premium Room",
    tagline: "Deep cleans, tighter turnarounds, better matches.",
    priceMonthly: 79,
    perks: [
      "Everything in Basic",
      "Up to 6 bookings per month",
      "Voice + video walkthrough calls",
      "Next-day scheduling",
      "Deep clean & move-out add-ons",
      "Priority support in 4h",
    ],
    visitFeeRange: [55, 85],
    specialistCount: 46,
    seatsLeft: 38,
  },
  {
    id: "ultimate",
    name: "Ultimate Room",
    tagline: "A dedicated team on standby for your home.",
    priceMonthly: 189,
    perks: [
      "Everything in Premium",
      "Unlimited bookings",
      "Top-rated specialists only (4.9+)",
      "Same-day dispatch window",
      "Dedicated account manager",
      "Recurring schedules & key handling",
      "Damage protection up to GH₵5,000",
    ],
    visitFeeRange: [85, 140],
    specialistCount: 19,
    seatsLeft: 7,
  },
];

export const specialists: Specialist[] = [
  {
    id: "sp-01",
    name: "Amara Osei",
    city: "Brooklyn, NY",
    room: "ultimate",
    headline: "Deep-clean lead with 9 years in luxury residential",
    bio: "I run detail-first deep cleans for brownstones and lofts. Eco products by default, and I document every room before and after.",
    rating: 4.97,
    jobsCompleted: 412,
    hourlyRate: 68,
    yearsExperience: 9,
    services: ["Deep clean", "Move-out", "Post-renovation", "Recurring"],
    languages: ["English", "Twi"],
    verified: true,
    online: true,
    responseMinutes: 4,
  },
  {
    id: "sp-02",
    name: "Lucia Ferrante",
    city: "Jersey City, NJ",
    room: "premium",
    headline: "Kitchens and bathrooms specialist, same-week slots",
    bio: "Ex-hospitality housekeeping supervisor. I'm fast without cutting corners and I love a hard-water stain challenge.",
    rating: 4.91,
    jobsCompleted: 268,
    hourlyRate: 52,
    yearsExperience: 6,
    services: ["Standard clean", "Deep clean", "Appliance detail"],
    languages: ["English", "Italian"],
    verified: true,
    online: true,
    responseMinutes: 9,
  },
  {
    id: "sp-03",
    name: "Nadia Rahman",
    city: "Queens, NY",
    room: "premium",
    headline: "Recurring weekly upkeep for busy households",
    bio: "I keep homes steady week to week — laundry, linens, floors, and a tidy reset you can actually maintain.",
    rating: 4.88,
    jobsCompleted: 331,
    hourlyRate: 46,
    yearsExperience: 7,
    services: ["Recurring", "Laundry", "Standard clean", "Organising"],
    languages: ["English", "Bengali"],
    verified: true,
    online: false,
    responseMinutes: 21,
  },
  {
    id: "sp-04",
    name: "Grace Mwangi",
    city: "Newark, NJ",
    room: "basic",
    headline: "Reliable standard cleans, flexible evenings",
    bio: "Evening and weekend availability. Straightforward, thorough standard cleans for apartments up to 2 bedrooms.",
    rating: 4.79,
    jobsCompleted: 154,
    hourlyRate: 38,
    yearsExperience: 4,
    services: ["Standard clean", "Laundry"],
    languages: ["English", "Swahili"],
    verified: true,
    online: true,
    responseMinutes: 14,
  },
  {
    id: "sp-05",
    name: "Marta Kowalska",
    city: "Manhattan, NY",
    room: "ultimate",
    headline: "Private-residence housekeeping, discreet and documented",
    bio: "Full housekeeping for occupied residences: surfaces, wardrobes, kitchen systems, and a written handover after each visit.",
    rating: 4.99,
    jobsCompleted: 503,
    hourlyRate: 82,
    yearsExperience: 12,
    services: ["Housekeeping", "Deep clean", "Recurring", "Key handling"],
    languages: ["English", "Polish"],
    verified: true,
    online: true,
    responseMinutes: 3,
  },
  {
    id: "sp-06",
    name: "Selam Bekele",
    city: "Bronx, NY",
    room: "basic",
    headline: "Move-in and move-out turnarounds",
    bio: "Empty-unit specialist. Cabinets, baseboards, appliance interiors — the stuff inspections actually check.",
    rating: 4.72,
    jobsCompleted: 98,
    hourlyRate: 35,
    yearsExperience: 3,
    services: ["Move-out", "Standard clean"],
    languages: ["English", "Amharic"],
    verified: true,
    online: false,
    responseMinutes: 33,
  },
  {
    id: "sp-07",
    name: "Priya Nair",
    city: "Hoboken, NJ",
    room: "premium",
    headline: "Post-renovation dust removal done properly",
    bio: "HEPA extraction, multi-pass wipe-downs, and air-quality checks after contractors leave.",
    rating: 4.93,
    jobsCompleted: 187,
    hourlyRate: 58,
    yearsExperience: 8,
    services: ["Post-renovation", "Deep clean", "Window detail"],
    languages: ["English", "Malayalam", "Hindi"],
    verified: true,
    online: true,
    responseMinutes: 7,
  },
  {
    id: "sp-08",
    name: "Yasmin Haddad",
    city: "Brooklyn, NY",
    room: "ultimate",
    headline: "Team lead — two-person crews for large homes",
    bio: "I bring a vetted second cleaner for anything over 2,500 sq ft so you get a full reset in a single visit.",
    rating: 4.95,
    jobsCompleted: 289,
    hourlyRate: 74,
    yearsExperience: 10,
    services: ["Deep clean", "Housekeeping", "Recurring", "Event reset"],
    languages: ["English", "Arabic", "French"],
    verified: true,
    online: true,
    responseMinutes: 5,
  },
];

export const clients: Client[] = [
  {
    id: "cl-01",
    name: "Daniel Whitfield",
    city: "Brooklyn, NY",
    room: "premium",
    joined: "2026-02-11",
    subscriptionStatus: "active",
    lifetimeSpend: 1840,
    bookings: 14,
    },
  {
    id: "cl-02",
    name: "Tomas Alvarez",
    city: "Manhattan, NY",
    room: "ultimate",
    joined: "2025-11-03",
    subscriptionStatus: "active",
    lifetimeSpend: 6420,
    bookings: 41,
  },
  {
    id: "cl-03",
    name: "Ibrahim Sesay",
    city: "Newark, NJ",
    room: "basic",
    joined: "2026-05-20",
    subscriptionStatus: "past_due",
    lifetimeSpend: 320,
    bookings: 4,
  },
  {
    id: "cl-04",
    name: "Owen Bradley",
    city: "Hoboken, NJ",
    room: "premium",
    joined: "2026-01-08",
    subscriptionStatus: "active",
    lifetimeSpend: 2260,
    bookings: 19,
  },
  {
    id: "cl-05",
    name: "Kenji Watanabe",
    city: "Queens, NY",
    room: "basic",
    joined: "2026-06-27",
    subscriptionStatus: "cancelled",
    lifetimeSpend: 145,
    bookings: 2,
  },
];

export const applicants: Applicant[] = [
  {
    id: "ap-01",
    name: "Farida Bello",
    role: "specialist",
    city: "Brooklyn, NY",
    appliedAt: "2026-07-29",
    status: "in_review",
    idVerified: true,
    backgroundCheck: "clear",
    referenceChecks: 3,
    suggestedRoom: "premium",
    note: "6 years hotel housekeeping. Strong references, wants weekday work.",
  },
  {
    id: "ap-02",
    name: "Chidera Nwosu",
    role: "specialist",
    city: "Queens, NY",
    appliedAt: "2026-07-30",
    status: "pending",
    idVerified: true,
    backgroundCheck: "pending",
    referenceChecks: 1,
    suggestedRoom: "basic",
    note: "New to platform, 2 years private ash work. Awaiting second reference.",
  },
  {
    id: "ap-03",
    name: "Elena Petrova",
    role: "specialist",
    city: "Manhattan, NY",
    appliedAt: "2026-07-28",
    status: "in_review",
    idVerified: true,
    backgroundCheck: "clear",
    referenceChecks: 4,
    suggestedRoom: "ultimate",
    note: "11 years private residences, insured, key-handling experience.",
  },
  {
    id: "ap-04",
    name: "Marcus Deveaux",
    role: "client",
    city: "Jersey City, NJ",
    appliedAt: "2026-07-30",
    status: "pending",
    idVerified: false,
    backgroundCheck: "pending",
    referenceChecks: 0,
    suggestedRoom: "basic",
    note: "Subscription intent: Basic. ID upload blurry — re-request.",
  },
  {
    id: "ap-05",
    name: "Peter Lindqvist",
    role: "client",
    city: "Manhattan, NY",
    appliedAt: "2026-07-27",
    status: "in_review",
    idVerified: true,
    backgroundCheck: "clear",
    referenceChecks: 0,
    suggestedRoom: "ultimate",
    note: "Paid Ultimate deposit. 4,200 sq ft townhouse, wants recurring crew.",
  },
  {
    id: "ap-06",
    name: "Dmitri Volkov",
    role: "client",
    city: "Bronx, NY",
    appliedAt: "2026-07-26",
    status: "rejected",
    idVerified: true,
    backgroundCheck: "flagged",
    referenceChecks: 0,
    suggestedRoom: "basic",
    note: "Background check flagged. Rejected per trust & safety policy.",
  },
];

export const threads: Thread[] = [
  {
    id: "th-01",
    specialistId: "sp-01",
    clientId: CURRENT_CLIENT_ID,
    lastMessage: "Sure — I can start at 9am Saturday. Send a photo of the kitchen?",
    lastAt: "2026-07-31T18:42:00Z",
    unread: 2,
  },
  {
    id: "th-02",
    specialistId: "sp-02",
    clientId: CURRENT_CLIENT_ID,
    lastMessage: "The hard-water marks will need two passes, that's fine.",
    lastAt: "2026-07-31T15:10:00Z",
    unread: 0,
  },
  {
    id: "th-03",
    specialistId: "sp-07",
    clientId: CURRENT_CLIENT_ID,
    lastMessage: "Booking completed — thanks Daniel, receipt is in your history.",
    lastAt: "2026-07-29T21:05:00Z",
    unread: 0,
  },
];

export const messages: ChatMessage[] = [
  {
    id: "ms-01",
    threadId: "th-01",
    authorId: "system",
    body: "You're both verified members of the Ultimate room. Payments and scheduling stay inside Ashnight.",
    at: "2026-07-31T18:20:00Z",
    kind: "system",
  },
  {
    id: "ms-02",
    threadId: "th-01",
    authorId: CURRENT_CLIENT_ID,
    body: "Hi Amara — 2 bed / 2 bath in Fort Greene. Looking for a full deep clean before guests arrive next week.",
    at: "2026-07-31T18:22:00Z",
    kind: "text",
  },
  {
    id: "ms-03",
    threadId: "th-01",
    authorId: "sp-01",
    body: "Happy to take it. For that size a deep clean is usually 5 hours, including inside the oven and fridge.",
    at: "2026-07-31T18:26:00Z",
    kind: "text",
  },
  {
    id: "ms-04",
    threadId: "th-01",
    authorId: CURRENT_CLIENT_ID,
    body: "Perfect. Can you also do the balcony windows?",
    at: "2026-07-31T18:31:00Z",
    kind: "text",
  },
  {
    id: "ms-05",
    threadId: "th-01",
    authorId: "sp-01",
    body: "Yes — I'll add window detail as an add-on. Send the request whenever you're ready and I'll confirm the slot.",
    at: "2026-07-31T18:36:00Z",
    kind: "text",
  },
  {
    id: "ms-06",
    threadId: "th-01",
    authorId: "sp-01",
    body: "Sure — I can start at 9am Saturday. Send a photo of the kitchen?",
    at: "2026-07-31T18:42:00Z",
    kind: "text",
  },
  {
    id: "ms-07",
    threadId: "th-02",
    authorId: CURRENT_CLIENT_ID,
    body: "The shower glass has heavy limescale — is that something you handle?",
    at: "2026-07-31T15:02:00Z",
    kind: "text",
  },
  {
    id: "ms-08",
    threadId: "th-02",
    authorId: "sp-02",
    body: "The hard-water marks will need two passes, that's fine.",
    at: "2026-07-31T15:10:00Z",
    kind: "text",
  },
  {
    id: "ms-09",
    threadId: "th-03",
    authorId: "sp-07",
    body: "Booking completed — thanks Daniel, receipt is in your history.",
    at: "2026-07-29T21:05:00Z",
    kind: "text",
  },
];

export const bookings: Booking[] = [
  {
    id: "bk-01",
    threadId: "th-03",
    clientId: CURRENT_CLIENT_ID,
    specialistId: "sp-07",
    service: "Post-renovation clean",
    scheduledFor: "2026-07-29T13:00:00Z",
    hours: 6,
    rate: 58,
    addons: ["Window detail"],
    status: "completed",
    platformFeePct: 12,
  },
  {
    id: "bk-02",
    threadId: "th-02",
    clientId: CURRENT_CLIENT_ID,
    specialistId: "sp-02",
    service: "Deep clean — bathrooms",
    scheduledFor: "2026-08-04T14:00:00Z",
    hours: 3,
    rate: 52,
    addons: [],
    status: "paid",
    platformFeePct: 12,
  },
  {
    id: "bk-03",
    threadId: "th-01",
    clientId: "cl-02",
    specialistId: "sp-05",
    service: "Recurring housekeeping",
    scheduledFor: "2026-08-02T09:00:00Z",
    hours: 4,
    rate: 82,
    addons: ["Laundry"],
    status: "accepted",
    platformFeePct: 12,
  },
  {
    id: "bk-04",
    threadId: "th-02",
    clientId: "cl-04",
    specialistId: "sp-03",
    service: "Standard clean",
    scheduledFor: "2026-08-01T17:00:00Z",
    hours: 2,
    rate: 46,
    addons: [],
    status: "requested",
    platformFeePct: 12,
  },
  {
    id: "bk-05",
    threadId: "th-03",
    clientId: "cl-03",
    specialistId: "sp-04",
    service: "Move-out clean",
    scheduledFor: "2026-07-25T10:00:00Z",
    hours: 5,
    rate: 38,
    addons: ["Inside cabinets"],
    status: "disputed",
    platformFeePct: 12,
  },
];

export const SERVICE_CATALOG = [
  { id: "standard", label: "Standard clean", baseHours: 2 },
  { id: "deep", label: "Deep clean", baseHours: 5 },
  { id: "move", label: "Move-in / move-out", baseHours: 5 },
  { id: "reno", label: "Post-renovation clean", baseHours: 6 },
  { id: "housekeeping", label: "Housekeeping visit", baseHours: 4 },
  { id: "recurring", label: "Recurring weekly upkeep", baseHours: 3 },
] as const;

export const ADDON_CATALOG = [
  { id: "windows", label: "Window detail", price: 45 },
  { id: "oven", label: "Inside oven", price: 35 },
  { id: "fridge", label: "Inside fridge", price: 30 },
  { id: "cabinets", label: "Inside cabinets", price: 40 },
  { id: "laundry", label: "Laundry & linens", price: 25 },
] as const;

/* ---------------------------------- selectors --------------------------------- */

export const getSpecialist = (id: string) => specialists.find((s) => s.id === id);
export const getClient = (id: string) => clients.find((c) => c.id === id);
export const getRoom = (id: string) => rooms.find((r) => r.id === id);
export const getThread = (id: string) => threads.find((t) => t.id === id);
export const getThreadMessages = (threadId: string) =>
  messages.filter((m) => m.threadId === threadId);
export const currentClient = () => clients.find((c) => c.id === CURRENT_CLIENT_ID)!;

export const adminMetrics = () => {
  const activeSubs = clients.filter((c) => c.subscriptionStatus === "active").length;
  const mrr = clients
    .filter((c) => c.subscriptionStatus === "active")
    .reduce((sum, c) => sum + (getRoom(c.room)?.priceMonthly ?? 0), 0);
  const gmv = bookings
    .filter((b) => b.status === "paid" || b.status === "completed")
    .reduce((sum, b) => sum + b.hours * b.rate, 0);
  return {
    activeSubs,
    mrr,
    gmv,
    takeRate: 12,
    pendingVetting: applicants.filter(
      (a) => a.status === "pending" || a.status === "in_review",
    ).length,
    openDisputes: bookings.filter((b) => b.status === "disputed").length,
    specialists: specialists.length,
  };
};

export const bookingTrend = [
  { month: "Feb", bookings: 96, gmv: 21400 },
  { month: "Mar", bookings: 128, gmv: 28900 },
  { month: "Apr", bookings: 164, gmv: 37200 },
  { month: "May", bookings: 189, gmv: 44100 },
  { month: "Jun", bookings: 231, gmv: 55600 },
  { month: "Jul", bookings: 274, gmv: 67300 },
];

export const roomDistribution = () =>
  rooms.map((room) => ({
    room: room.name.replace(" Room", ""),
    clients: clients.filter((c) => c.room === room.id).length,
    specialists: specialists.filter((s) => s.room === room.id).length,
  }));
