/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AshnightControlRouteImport } from './routes/ashnight-control'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AshnightControlIndexRouteImport } from './routes/ashnight-control.index'
import { Route as AshnightControlBackupsRouteImport } from './routes/ashnight-control.backups'
import { Route as AshnightControlBookingsRouteImport } from './routes/ashnight-control.bookings'
import { Route as AshnightControlComplaintsRouteImport } from './routes/ashnight-control.complaints'
import { Route as AshnightControlDocumentsRouteImport } from './routes/ashnight-control.documents'
import { Route as AshnightControlEscrowRouteImport } from './routes/ashnight-control.escrow'
import { Route as AshnightControlFeaturesRouteImport } from './routes/ashnight-control.features'
import { Route as AshnightControlLogsRouteImport } from './routes/ashnight-control.logs'
import { Route as AshnightControlModerationRouteImport } from './routes/ashnight-control.moderation'
import { Route as AshnightControlNotificationsRouteImport } from './routes/ashnight-control.notifications'
import { Route as AshnightControlRoomsRouteImport } from './routes/ashnight-control.rooms'
import { Route as AshnightControlServerRouteImport } from './routes/ashnight-control.server'
import { Route as AshnightControlServicesRouteImport } from './routes/ashnight-control.services'
import { Route as AshnightControlSettingsRouteImport } from './routes/ashnight-control.settings'
import { Route as AshnightControlSignupRouteImport } from './routes/ashnight-control.signup'
import { Route as AshnightControlUsersRouteImport } from './routes/ashnight-control.users'
import { Route as AshnightControlVettingRouteImport } from './routes/ashnight-control.vetting'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as SpecialistsIndexRouteImport } from './routes/specialists.index'
import { Route as SpecialistsSpecialistIdRouteImport } from './routes/specialists.$specialistId'
import { Route as ApiPublicHooksBackupRouteImport } from './routes/api/public/hooks/backup'
import { Route as ApiPublicHooksEscrowReleaseRouteImport } from './routes/api/public/hooks/escrow-release'
import { Route as ApiPublicHooksPaystackRouteImport } from './routes/api/public/hooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AshnightControlRoute = AshnightControlRouteImport.update({
  id: '/ashnight-control',
  path: '/ashnight-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AshnightControlIndexRoute = AshnightControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlBackupsRoute = AshnightControlBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlBookingsRoute = AshnightControlBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlComplaintsRoute =
  AshnightControlComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => AshnightControlRoute,
  } as any)
const AshnightControlDocumentsRoute =
  AshnightControlDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AshnightControlRoute,
  } as any)
const AshnightControlEscrowRoute = AshnightControlEscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlFeaturesRoute = AshnightControlFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlLogsRoute = AshnightControlLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlModerationRoute =
  AshnightControlModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AshnightControlRoute,
  } as any)
const AshnightControlNotificationsRoute =
  AshnightControlNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AshnightControlRoute,
  } as any)
const AshnightControlRoomsRoute = AshnightControlRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlServerRoute = AshnightControlServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlServicesRoute = AshnightControlServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlSettingsRoute = AshnightControlSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlSignupRoute = AshnightControlSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlUsersRoute = AshnightControlUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AshnightControlRoute,
} as any)
const AshnightControlVettingRoute = AshnightControlVettingRouteImport.update({
  id: '/vetting',
  path: '/vetting',
  getParentRoute: () => AshnightControlRoute,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsIndexRoute = SpecialistsIndexRouteImport.update({
  id: '/specialists/',
  path: '/specialists/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsSpecialistIdRoute = SpecialistsSpecialistIdRouteImport.update({
  id: '/specialists/$specialistId',
  path: '/specialists/$specialistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackupRoute = ApiPublicHooksBackupRouteImport.update({
  id: '/api/public/hooks/backup',
  path: '/api/public/hooks/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEscrowReleaseRoute =
  ApiPublicHooksEscrowReleaseRouteImport.update({
    id: '/api/public/hooks/escrow-release',
    path: '/api/public/hooks/escrow-release',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaystackRoute = ApiPublicHooksPaystackRouteImport.update({
  id: '/api/public/hooks/paystack',
  path: '/api/public/hooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/ashnight-control': typeof AshnightControlRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/support': typeof SupportRoute
  '/ashnight-control/backups': typeof AshnightControlBackupsRoute
  '/ashnight-control/bookings': typeof AshnightControlBookingsRoute
  '/ashnight-control/complaints': typeof AshnightControlComplaintsRoute
  '/ashnight-control/documents': typeof AshnightControlDocumentsRoute
  '/ashnight-control/escrow': typeof AshnightControlEscrowRoute
  '/ashnight-control/features': typeof AshnightControlFeaturesRoute
  '/ashnight-control/logs': typeof AshnightControlLogsRoute
  '/ashnight-control/moderation': typeof AshnightControlModerationRoute
  '/ashnight-control/notifications': typeof AshnightControlNotificationsRoute
  '/ashnight-control/rooms': typeof AshnightControlRoomsRoute
  '/ashnight-control/server': typeof AshnightControlServerRoute
  '/ashnight-control/services': typeof AshnightControlServicesRoute
  '/ashnight-control/settings': typeof AshnightControlSettingsRoute
  '/ashnight-control/signup': typeof AshnightControlSignupRoute
  '/ashnight-control/users': typeof AshnightControlUsersRoute
  '/ashnight-control/vetting': typeof AshnightControlVettingRoute
  '/payment/return': typeof PaymentReturnRoute
  '/specialists/$specialistId': typeof SpecialistsSpecialistIdRoute
  '/ashnight-control/': typeof AshnightControlIndexRoute
  '/specialists/': typeof SpecialistsIndexRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
  '/api/public/hooks/escrow-release': typeof ApiPublicHooksEscrowReleaseRoute
  '/api/public/hooks/paystack': typeof ApiPublicHooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/support': typeof SupportRoute
  '/ashnight-control/backups': typeof AshnightControlBackupsRoute
  '/ashnight-control/bookings': typeof AshnightControlBookingsRoute
  '/ashnight-control/complaints': typeof AshnightControlComplaintsRoute
  '/ashnight-control/documents': typeof AshnightControlDocumentsRoute
  '/ashnight-control/escrow': typeof AshnightControlEscrowRoute
  '/ashnight-control/features': typeof AshnightControlFeaturesRoute
  '/ashnight-control/logs': typeof AshnightControlLogsRoute
  '/ashnight-control/moderation': typeof AshnightControlModerationRoute
  '/ashnight-control/notifications': typeof AshnightControlNotificationsRoute
  '/ashnight-control/rooms': typeof AshnightControlRoomsRoute
  '/ashnight-control/server': typeof AshnightControlServerRoute
  '/ashnight-control/services': typeof AshnightControlServicesRoute
  '/ashnight-control/settings': typeof AshnightControlSettingsRoute
  '/ashnight-control/signup': typeof AshnightControlSignupRoute
  '/ashnight-control/users': typeof AshnightControlUsersRoute
  '/ashnight-control/vetting': typeof AshnightControlVettingRoute
  '/payment/return': typeof PaymentReturnRoute
  '/specialists/$specialistId': typeof SpecialistsSpecialistIdRoute
  '/ashnight-control': typeof AshnightControlIndexRoute
  '/specialists': typeof SpecialistsIndexRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
  '/api/public/hooks/escrow-release': typeof ApiPublicHooksEscrowReleaseRoute
  '/api/public/hooks/paystack': typeof ApiPublicHooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/ashnight-control': typeof AshnightControlRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/support': typeof SupportRoute
  '/ashnight-control/backups': typeof AshnightControlBackupsRoute
  '/ashnight-control/bookings': typeof AshnightControlBookingsRoute
  '/ashnight-control/complaints': typeof AshnightControlComplaintsRoute
  '/ashnight-control/documents': typeof AshnightControlDocumentsRoute
  '/ashnight-control/escrow': typeof AshnightControlEscrowRoute
  '/ashnight-control/features': typeof AshnightControlFeaturesRoute
  '/ashnight-control/logs': typeof AshnightControlLogsRoute
  '/ashnight-control/moderation': typeof AshnightControlModerationRoute
  '/ashnight-control/notifications': typeof AshnightControlNotificationsRoute
  '/ashnight-control/rooms': typeof AshnightControlRoomsRoute
  '/ashnight-control/server': typeof AshnightControlServerRoute
  '/ashnight-control/services': typeof AshnightControlServicesRoute
  '/ashnight-control/settings': typeof AshnightControlSettingsRoute
  '/ashnight-control/signup': typeof AshnightControlSignupRoute
  '/ashnight-control/users': typeof AshnightControlUsersRoute
  '/ashnight-control/vetting': typeof AshnightControlVettingRoute
  '/payment/return': typeof PaymentReturnRoute
  '/specialists/$specialistId': typeof SpecialistsSpecialistIdRoute
  '/ashnight-control/': typeof AshnightControlIndexRoute
  '/specialists/': typeof SpecialistsIndexRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
  '/api/public/hooks/escrow-release': typeof ApiPublicHooksEscrowReleaseRoute
  '/api/public/hooks/paystack': typeof ApiPublicHooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/ashnight-control'
    | '/auth'
    | '/how-it-works'
    | '/legal'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/rooms'
    | '/support'
    | '/ashnight-control/backups'
    | '/ashnight-control/bookings'
    | '/ashnight-control/complaints'
    | '/ashnight-control/documents'
    | '/ashnight-control/escrow'
    | '/ashnight-control/features'
    | '/ashnight-control/logs'
    | '/ashnight-control/moderation'
    | '/ashnight-control/notifications'
    | '/ashnight-control/rooms'
    | '/ashnight-control/server'
    | '/ashnight-control/services'
    | '/ashnight-control/settings'
    | '/ashnight-control/signup'
    | '/ashnight-control/users'
    | '/ashnight-control/vetting'
    | '/payment/return'
    | '/specialists/$specialistId'
    | '/ashnight-control/'
    | '/specialists/'
    | '/api/public/hooks/backup'
    | '/api/public/hooks/escrow-release'
    | '/api/public/hooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/how-it-works'
    | '/legal'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/rooms'
    | '/support'
    | '/ashnight-control/backups'
    | '/ashnight-control/bookings'
    | '/ashnight-control/complaints'
    | '/ashnight-control/documents'
    | '/ashnight-control/escrow'
    | '/ashnight-control/features'
    | '/ashnight-control/logs'
    | '/ashnight-control/moderation'
    | '/ashnight-control/notifications'
    | '/ashnight-control/rooms'
    | '/ashnight-control/server'
    | '/ashnight-control/services'
    | '/ashnight-control/settings'
    | '/ashnight-control/signup'
    | '/ashnight-control/users'
    | '/ashnight-control/vetting'
    | '/payment/return'
    | '/specialists/$specialistId'
    | '/ashnight-control'
    | '/specialists'
    | '/api/public/hooks/backup'
    | '/api/public/hooks/escrow-release'
    | '/api/public/hooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/ashnight-control'
    | '/auth'
    | '/how-it-works'
    | '/legal'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/rooms'
    | '/support'
    | '/ashnight-control/backups'
    | '/ashnight-control/bookings'
    | '/ashnight-control/complaints'
    | '/ashnight-control/documents'
    | '/ashnight-control/escrow'
    | '/ashnight-control/features'
    | '/ashnight-control/logs'
    | '/ashnight-control/moderation'
    | '/ashnight-control/notifications'
    | '/ashnight-control/rooms'
    | '/ashnight-control/server'
    | '/ashnight-control/services'
    | '/ashnight-control/settings'
    | '/ashnight-control/signup'
    | '/ashnight-control/users'
    | '/ashnight-control/vetting'
    | '/payment/return'
    | '/specialists/$specialistId'
    | '/ashnight-control/'
    | '/specialists/'
    | '/api/public/hooks/backup'
    | '/api/public/hooks/escrow-release'
    | '/api/public/hooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  AshnightControlRoute: typeof AshnightControlRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LegalRoute: typeof LegalRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomsRoute: typeof RoomsRoute
  SupportRoute: typeof SupportRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  SpecialistsSpecialistIdRoute: typeof SpecialistsSpecialistIdRoute
  SpecialistsIndexRoute: typeof SpecialistsIndexRoute
  ApiPublicHooksBackupRoute: typeof ApiPublicHooksBackupRoute
  ApiPublicHooksEscrowReleaseRoute: typeof ApiPublicHooksEscrowReleaseRoute
  ApiPublicHooksPaystackRoute: typeof ApiPublicHooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ashnight-control': {
      id: '/ashnight-control'
      path: '/ashnight-control'
      fullPath: '/ashnight-control'
      preLoaderRoute: typeof AshnightControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ashnight-control/': {
      id: '/ashnight-control/'
      path: '/'
      fullPath: '/ashnight-control/'
      preLoaderRoute: typeof AshnightControlIndexRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/backups': {
      id: '/ashnight-control/backups'
      path: '/backups'
      fullPath: '/ashnight-control/backups'
      preLoaderRoute: typeof AshnightControlBackupsRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/bookings': {
      id: '/ashnight-control/bookings'
      path: '/bookings'
      fullPath: '/ashnight-control/bookings'
      preLoaderRoute: typeof AshnightControlBookingsRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/complaints': {
      id: '/ashnight-control/complaints'
      path: '/complaints'
      fullPath: '/ashnight-control/complaints'
      preLoaderRoute: typeof AshnightControlComplaintsRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/documents': {
      id: '/ashnight-control/documents'
      path: '/documents'
      fullPath: '/ashnight-control/documents'
      preLoaderRoute: typeof AshnightControlDocumentsRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/escrow': {
      id: '/ashnight-control/escrow'
      path: '/escrow'
      fullPath: '/ashnight-control/escrow'
      preLoaderRoute: typeof AshnightControlEscrowRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/features': {
      id: '/ashnight-control/features'
      path: '/features'
      fullPath: '/ashnight-control/features'
      preLoaderRoute: typeof AshnightControlFeaturesRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/logs': {
      id: '/ashnight-control/logs'
      path: '/logs'
      fullPath: '/ashnight-control/logs'
      preLoaderRoute: typeof AshnightControlLogsRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/moderation': {
      id: '/ashnight-control/moderation'
      path: '/moderation'
      fullPath: '/ashnight-control/moderation'
      preLoaderRoute: typeof AshnightControlModerationRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/notifications': {
      id: '/ashnight-control/notifications'
      path: '/notifications'
      fullPath: '/ashnight-control/notifications'
      preLoaderRoute: typeof AshnightControlNotificationsRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/rooms': {
      id: '/ashnight-control/rooms'
      path: '/rooms'
      fullPath: '/ashnight-control/rooms'
      preLoaderRoute: typeof AshnightControlRoomsRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/server': {
      id: '/ashnight-control/server'
      path: '/server'
      fullPath: '/ashnight-control/server'
      preLoaderRoute: typeof AshnightControlServerRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/services': {
      id: '/ashnight-control/services'
      path: '/services'
      fullPath: '/ashnight-control/services'
      preLoaderRoute: typeof AshnightControlServicesRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/settings': {
      id: '/ashnight-control/settings'
      path: '/settings'
      fullPath: '/ashnight-control/settings'
      preLoaderRoute: typeof AshnightControlSettingsRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/signup': {
      id: '/ashnight-control/signup'
      path: '/signup'
      fullPath: '/ashnight-control/signup'
      preLoaderRoute: typeof AshnightControlSignupRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/users': {
      id: '/ashnight-control/users'
      path: '/users'
      fullPath: '/ashnight-control/users'
      preLoaderRoute: typeof AshnightControlUsersRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/ashnight-control/vetting': {
      id: '/ashnight-control/vetting'
      path: '/vetting'
      fullPath: '/ashnight-control/vetting'
      preLoaderRoute: typeof AshnightControlVettingRouteImport
      parentRoute: typeof AshnightControlRoute
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists/': {
      id: '/specialists/'
      path: '/specialists'
      fullPath: '/specialists/'
      preLoaderRoute: typeof SpecialistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists/$specialistId': {
      id: '/specialists/$specialistId'
      path: '/specialists/$specialistId'
      fullPath: '/specialists/$specialistId'
      preLoaderRoute: typeof SpecialistsSpecialistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backup': {
      id: '/api/public/hooks/backup'
      path: '/api/public/hooks/backup'
      fullPath: '/api/public/hooks/backup'
      preLoaderRoute: typeof ApiPublicHooksBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/escrow-release': {
      id: '/api/public/hooks/escrow-release'
      path: '/api/public/hooks/escrow-release'
      fullPath: '/api/public/hooks/escrow-release'
      preLoaderRoute: typeof ApiPublicHooksEscrowReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/paystack': {
      id: '/api/public/hooks/paystack'
      path: '/api/public/hooks/paystack'
      fullPath: '/api/public/hooks/paystack'
      preLoaderRoute: typeof ApiPublicHooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AshnightControlRouteChildren {
  AshnightControlBackupsRoute: typeof AshnightControlBackupsRoute
  AshnightControlBookingsRoute: typeof AshnightControlBookingsRoute
  AshnightControlComplaintsRoute: typeof AshnightControlComplaintsRoute
  AshnightControlDocumentsRoute: typeof AshnightControlDocumentsRoute
  AshnightControlEscrowRoute: typeof AshnightControlEscrowRoute
  AshnightControlFeaturesRoute: typeof AshnightControlFeaturesRoute
  AshnightControlLogsRoute: typeof AshnightControlLogsRoute
  AshnightControlModerationRoute: typeof AshnightControlModerationRoute
  AshnightControlNotificationsRoute: typeof AshnightControlNotificationsRoute
  AshnightControlRoomsRoute: typeof AshnightControlRoomsRoute
  AshnightControlServerRoute: typeof AshnightControlServerRoute
  AshnightControlServicesRoute: typeof AshnightControlServicesRoute
  AshnightControlSettingsRoute: typeof AshnightControlSettingsRoute
  AshnightControlSignupRoute: typeof AshnightControlSignupRoute
  AshnightControlUsersRoute: typeof AshnightControlUsersRoute
  AshnightControlVettingRoute: typeof AshnightControlVettingRoute
  AshnightControlIndexRoute: typeof AshnightControlIndexRoute
}

const AshnightControlRouteChildren: AshnightControlRouteChildren = {
  AshnightControlBackupsRoute: AshnightControlBackupsRoute,
  AshnightControlBookingsRoute: AshnightControlBookingsRoute,
  AshnightControlComplaintsRoute: AshnightControlComplaintsRoute,
  AshnightControlDocumentsRoute: AshnightControlDocumentsRoute,
  AshnightControlEscrowRoute: AshnightControlEscrowRoute,
  AshnightControlFeaturesRoute: AshnightControlFeaturesRoute,
  AshnightControlLogsRoute: AshnightControlLogsRoute,
  AshnightControlModerationRoute: AshnightControlModerationRoute,
  AshnightControlNotificationsRoute: AshnightControlNotificationsRoute,
  AshnightControlRoomsRoute: AshnightControlRoomsRoute,
  AshnightControlServerRoute: AshnightControlServerRoute,
  AshnightControlServicesRoute: AshnightControlServicesRoute,
  AshnightControlSettingsRoute: AshnightControlSettingsRoute,
  AshnightControlSignupRoute: AshnightControlSignupRoute,
  AshnightControlUsersRoute: AshnightControlUsersRoute,
  AshnightControlVettingRoute: AshnightControlVettingRoute,
  AshnightControlIndexRoute: AshnightControlIndexRoute,
}

const AshnightControlRouteWithChildren = AshnightControlRoute._addFileChildren(
  AshnightControlRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  AshnightControlRoute: AshnightControlRouteWithChildren,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  LegalRoute: LegalRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomsRoute: RoomsRoute,
  SupportRoute: SupportRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  SpecialistsSpecialistIdRoute: SpecialistsSpecialistIdRoute,
  SpecialistsIndexRoute: SpecialistsIndexRoute,
  ApiPublicHooksBackupRoute: ApiPublicHooksBackupRoute,
  ApiPublicHooksEscrowReleaseRoute: ApiPublicHooksEscrowReleaseRoute,
  ApiPublicHooksPaystackRoute: ApiPublicHooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
