/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVettingRouteImport } from './routes/admin.vetting'
import { Route as SpecialistsIndexRouteImport } from './routes/specialists.index'
import { Route as SpecialistsSpecialistIdRouteImport } from './routes/specialists.$specialistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVettingRoute = AdminVettingRouteImport.update({
  id: '/vetting',
  path: '/vetting',
  getParentRoute: () => AdminRoute,
} as any)
const SpecialistsIndexRoute = SpecialistsIndexRouteImport.update({
  id: '/specialists/',
  path: '/specialists/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialistsSpecialistIdRoute = SpecialistsSpecialistIdRouteImport.update({
  id: '/specialists/$specialistId',
  path: '/specialists/$specialistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/messages': typeof MessagesRoute
  '/rooms': typeof RoomsRoute
  '/admin/vetting': typeof AdminVettingRoute
  '/specialists/$specialistId': typeof SpecialistsSpecialistIdRoute
  '/admin/': typeof AdminIndexRoute
  '/specialists/': typeof SpecialistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/messages': typeof MessagesRoute
  '/rooms': typeof RoomsRoute
  '/admin/vetting': typeof AdminVettingRoute
  '/specialists/$specialistId': typeof SpecialistsSpecialistIdRoute
  '/admin': typeof AdminIndexRoute
  '/specialists': typeof SpecialistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/messages': typeof MessagesRoute
  '/rooms': typeof RoomsRoute
  '/admin/vetting': typeof AdminVettingRoute
  '/specialists/$specialistId': typeof SpecialistsSpecialistIdRoute
  '/admin/': typeof AdminIndexRoute
  '/specialists/': typeof SpecialistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/how-it-works'
    | '/messages'
    | '/rooms'
    | '/admin/vetting'
    | '/specialists/$specialistId'
    | '/admin/'
    | '/specialists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/how-it-works'
    | '/messages'
    | '/rooms'
    | '/admin/vetting'
    | '/specialists/$specialistId'
    | '/admin'
    | '/specialists'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/how-it-works'
    | '/messages'
    | '/rooms'
    | '/admin/vetting'
    | '/specialists/$specialistId'
    | '/admin/'
    | '/specialists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MessagesRoute: typeof MessagesRoute
  RoomsRoute: typeof RoomsRoute
  SpecialistsSpecialistIdRoute: typeof SpecialistsSpecialistIdRoute
  SpecialistsIndexRoute: typeof SpecialistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vetting': {
      id: '/admin/vetting'
      path: '/vetting'
      fullPath: '/admin/vetting'
      preLoaderRoute: typeof AdminVettingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/specialists/': {
      id: '/specialists/'
      path: '/specialists'
      fullPath: '/specialists/'
      preLoaderRoute: typeof SpecialistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialists/$specialistId': {
      id: '/specialists/$specialistId'
      path: '/specialists/$specialistId'
      fullPath: '/specialists/$specialistId'
      preLoaderRoute: typeof SpecialistsSpecialistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminVettingRoute: typeof AdminVettingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminVettingRoute: AdminVettingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  HowItWorksRoute: HowItWorksRoute,
  MessagesRoute: MessagesRoute,
  RoomsRoute: RoomsRoute,
  SpecialistsSpecialistIdRoute: SpecialistsSpecialistIdRoute,
  SpecialistsIndexRoute: SpecialistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
